.PHONY: harness-check

harness-check:
	python checks/validate_ci_policy.py
	python checks/validate_assurance_registry.py
	python checks/validate_cross_project_portability.py
	python tests/test_behavioral_eval.py
	python tests/test_behavioral_eval_cases.py
	python checks/validate_context_boundaries.py
	python tests/test_core.py
	python tests/test_adapters.py
	python tests/test_target_state.py
	python tests/test_engineering_graph.py
	python checks/validate_authority_catalog.py
	python checks/validate_authority_boundary_research.py
	python checks/validate_ddd_authority_research.py
	python checks/validate_reference_applicability_research.py
	python tests/test_reference_engineering_model.py
	python tests/test_reference_model_evolution.py
	python tests/test_specialization_proof_semantics.py
	python checks/validate_project_behavior_evals.py
	python checks/validate_project_engineering_status.py
	python tests/test_project_status_e2e.py
	python tests/test_agent_router.py
	python tests/test_workspace.py
	python checks/validate_agent_layer.py
	python checks/validate_instruction_ownership.py
	python tests/test_skill_router.py
	python tests/test_fresh_context_routing.py
	python tests/test_method_router.py
	python tests/test_source_coverage.py
	python tests/test_user_facing_application.py
	python tests/test_frontend_screen_contracts.py
	python tests/test_frontend_ux_closure.py
	python tests/test_unified_model.py
	python tests/test_graph_doctor.py
	python tests/test_human_projection.py
	python tests/test_structurizr_projection.py
	python tests/test_coverage_map_experiment.py
	python tests/test_coverage_derivation_experiment.py
	python tests/test_coverage_planner_experiment.py
	python checks/validate_concern_proof_model.py
	python tests/test_engineering_graph_semantic_claims_experiment.py
	python checks/validate_concern_activation_policy.py
	python tests/test_concern_activation_experiment.py
	python tests/test_coverage_control_loop_experiment.py
	python tests/test_concern_activation_scaling.py
	python tests/test_authority_role_projection_experiment.py
	python tests/test_consumer_scoped_activation.py
	python tests/test_consumer_scoped_coverage_proof.py
	python tests/test_intra_consumer_scope.py
	python tests/test_subject_scoped_coverage.py
	python tests/test_subject_obligations.py
	python tests/test_engineering_coverage.py
	python tests/test_repository_realization_design.py
	python tests/test_architecture_driver_closure.py
	python tests/test_coverage_blocker_transition.py
	python tests/test_coverage_production_contract_overlay.py
	python tests/test_semantic_acceptance.py
	python checks/validate_skill_invariant_policy.py
	python tests/test_capability_lifecycle.py
	python tests/test_deep_dependency_graphs.py
	python tests/test_decision_governance.py
	python tests/test_decision_pipeline.py
	python tests/test_project_frontier.py
	python tests/test_project_publication.py
	python tests/test_semantic_admission.py
	python tests/test_semantic_question_loop.py
	python tests/test_semantic_closure.py
	python checks/validate_harness.py
	python -m unittest tests/test_lifecycle_experiment.py
	python tests/test_consumer_pack.py
	python tests/test_consumer_wrapper.py
	python tests/test_scenario_suite.py
	python tests/test_live_calibration_process_driver.py
	python tests/test_copilot_live_calibration_evaluator.py
